services:
  nginx:
    image: ./requirements/nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443

  wordpress:
    image: ./requirements/wordpress
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    env_file:
      - .env

  mariadb:
    image: ./requirements/mariadb
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
