-- Delete Already Existing Root User on the Host
DELETE FROM
  mysql.user
WHERE
  User = '$MYSQL_HOSTNAME'
  AND Host NOT IN ('$HOST_NAME', '$HOST_IPV4', '$HOST_IPV6');

-- Set Password of Root User on MariaDB
SET
  PASSWORD FOR '$MYSQL_HOSTNAME'@'$HOST_NAME' = PASSWORD('$MYSQL_ROOT_PASSWORD');

-- Create WordPress Database
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;

-- Create Another User for WordPress
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';

-- Grant Permissions
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%' WITH GRANT OPTION;

-- Apply
FLUSH PRIVILEGES;